### ISSUE TITLE
Similar design with the new ISC site

### ISSUE THREAD

**Issue by voborgus** [InnerSourceCommons/InnerSourcePatterns#283] opened 2021-01-26 14:41 UTC
Since we're going to a subdomain (#250) will be great (if possible) to change the design of the git book
Not for 100% same with the website (currently at [innersourcecommons.net](http://innersourcecommons.net)) but at least copy colors and the header.

**Comment by spier** [comment] 2021-01-26 21:21
Thanks for sharing this idea @voborgus.

gitbook doesn't have that many design customization options, but let me share the ones available:

## Color

We can set one main color, which will change the color of the header and the links.
Based on what I see on https://innersourcecommons.net I used the dark green (`#0AA8A7`) for that.
I already set that at https://innersourcecommons.gitbook.io/innersource-patterns/, just waiting to refresh the CSS NOW.

That dark green (`#0AA8A7`) doesn't fit to the blue in our book cover any more but I don't really mind.
Maybe I can change the color of the cover at some point too :)

## Font

For fonts, gitbook has the ones shown in the screenshot below. Which font is https://innersourcecommons.net using or what comes closest to that?

![Screen Shot 2021-01-26 at 22 12 23 ](https://user-images.githubusercontent.com/163029/105906255-bf079880-6023-11eb-8a75-39ae6d234fa7.JPG)

## Header

What do you mean by that exactly?
Which part would you like to reproduce?

**Comment by voborgus** [comment] 2021-01-27 11:26
> What do you mean by that exactly?
Which part would you like to reproduce?

While saying header I mean something like:

![image](https://user-images.githubusercontent.com/9394918/105984363-0b49eb80-60ab-11eb-8cde-aabf426042c7.png)

But not sure it's possible with GitBook.

> For fonts, gitbook has the ones shown in the screenshot below. Which font is https://innersourcecommons.net using or what comes closest to that

Seems the closest one with the default ISC `PT Sans` font – `Lato`.

![image](https://user-images.githubusercontent.com/9394918/105984650-7eebf880-60ab-11eb-8227-c1a87aae01c2.png)

thanks for your help!

**Comment by spier** [comment] 2021-02-13 14:49
Hi @voborgus. 

I don't think I can reproduce the full header.
Maybe it is even better that way, as otherwise we would constantly have to check to keep website and gitbook in sync.

However I could use a logo at the top left of the gitbook that looks similar to the one that you have on the new website.

Could you create a logo similar to the one that you have on the website but instead of "Commons" it should say "Patterns"?
The dimensions for the logo in gitbook are:
* 232px width
* 40px height

What do you think about that idea?

**Comment by spier** [comment] 2021-02-26 17:45
Thanks for the logo! (got it via Slack)

The adapted design looks quite good now I think. 
Simplistic but very clean :)

![Screen Shot 2021-02-26 at 18 43 53 ](https://user-images.githubusercontent.com/163029/109335711-b2fd3980-7862-11eb-82be-706c4f00ef81.JPG)

**Comment by spier** [comment] 2021-02-26 17:46
I am closing this issue because I believe that this is the best we can do design-wise right now on the gitbook service.

Thanks for your help with this @voborgus ❤️

**Closed as completed by spier** 2021-02-26 17:46 UTC
Labels: (Self-) Hosting
