### ISSUE TITLE
Start Checklist for PR processing to ensure keeping the right things updated on changes 

### ISSUE THREAD

**Issue by lenucksi** [InnerSourceCommons/InnerSourcePatterns#163] opened 2020-05-06 19:12 UTC
#156 is great stuff, we just need to remember to add a GitHub Action to regenerate the SVG / HTML / rendered products once the .md changes and make a checklist item for PRs to update the .md once new things come in to keep everything fresh. 

_Originally posted by @lenucksi in https://github.com/InnerSourceCommons/InnerSourcePatterns/pull/156#issuecomment-624834371_

**Comment by spier** [comment] 2020-12-14 20:57
@lenucksi is this a duplicate of https://github.com/InnerSourceCommons/InnerSourcePatterns/issues/162?

**Comment by spier** [comment] 2021-02-14 11:24
Closing as duplicate.

**Closed as completed by spier** 2021-02-14 11:24 UTC
Labels: :gear: Type - Meta
